image: ghcr.io/sushrut1101/docker:latest

test:
    timeout: 1 month
    script:
        - nproc
        - nproc --all
        - neofetch || uname -a && uptime
        - df -h
        - lsblk
        - ls /dev
        - ls /dev/*/ || true
        - speedtest || true
